[package]
name = "rust_ggen"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
graph6-rs = "0.2.1"
itertools = "0.14.0"
rand = "0.9.1"
rayon = "1.10.0"
once_cell = "1.19.0"
nauty-Traces-sys = "0.9"
